import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import { useOrganization } from '../../contexts/OrganizationContext';

const navItems = [{ to: '/dashboard', label: 'Overview', icon: '◈' }, { to: '/services', label: 'Services', icon: '▦' }, { to: '/incidents', label: 'Incidents', icon: '!' }, { to: '/alerts', label: 'Alerts', icon: '⌁' }];
export function AppLayout() {
  const { user, logout } = useAuth(); const { organizations, selectedOrganization, selectOrganization } = useOrganization(); const navigate = useNavigate();
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">P</span><span>PulseOps</span></div><div className="workspace-label">WORKSPACE</div><select className="org-select" value={selectedOrganization?.id ?? ''} onChange={(event) => { selectOrganization(event.target.value); navigate('/dashboard'); }} aria-label="Current organization"><option value="" disabled>Select organization</option>{organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select><nav className="nav-list" aria-label="Primary navigation">{navItems.map((item) => <NavLink key={item.to} to={item.to} end={item.to === '/dashboard'} className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}><span className="nav-icon">{item.icon}</span>{item.label}</NavLink>)}</nav><div className="sidebar-foot"><span className="status-dot" />All systems connected</div></aside><div className="main-shell"><header className="topbar"><div><span className="eyebrow">OPERATIONS CENTER</span><span className="topbar-org">{selectedOrganization?.name ?? 'Select a workspace'}</span></div><div className="user-menu"><span className="avatar">{user?.name.slice(0, 1).toUpperCase()}</span><span className="user-copy"><strong>{user?.name}</strong><small>{user?.email}</small></span><button className="button ghost" onClick={() => { logout(); navigate('/login'); }}>Sign out</button></div></header><main className="content"><Outlet /></main></div></div>;
}
